# Basic Information 
title: Qinghao Shao
position: Undergraduate Student
affiliation: SYNU
email: hao2cyrus@gmail.com

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Qinghao Shao, 3D Computer Vision, 3DGS, Structure from Motion, AI Algorithms, Electronic Information Engineering, SYNU
description: Personal homepage of Qinghao Shao, focusing on 3D reconstruction
canonical: https://cyrush7.github.io/

# Links 
github_link: https://github.com/cyrush7
google_scholar: # 如果你有的话填这里，没有就留空
cv_link: # 如果有简历链接填这里

# 小红书配置 (变量名必须是 xiaohongshu_link)
xiaohongshu_link: https://www.xiaohongshu.com/user/profile/600036f20000000001002ad1?tab=note&subTab=note
xiaohongshu_icon: ./assets/img/xiaohongshu.jpg
xiaohongshu_icon_fallback: ./assets/img/xiaohongshu.jpg

# 微信配置 (变量名必须是 wechat_qr，并填入二维码图片路径)
wechat_qr: ./assets/img/wechat.jpg

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/master_ball.jpg
favicon_dark: ./assets/img/master_ball.jpg

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
